-- MySQL Script generated by MySQL Workbench
-- Sat May 11 19:58:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cash_register
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cash_register
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cash_register` DEFAULT CHARACTER SET utf8 ;
USE `cash_register` ;

-- -----------------------------------------------------
-- Table `cash_register`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_register`.`role` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `roleType` VARCHAR(45) NOT NULL,
                                                    PRIMARY KEY (`id`),
                                                    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cash_register`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_register`.`user` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `login` VARCHAR(45) NOT NULL,
                                                    `email` VARCHAR(45) NOT NULL,
                                                    `password` VARCHAR(45) NOT NULL,
                                                    `role_id` INT NOT NULL,
                                                    PRIMARY KEY (`id`, `role_id`),
                                                    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
                                                    INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
                                                    CONSTRAINT `fk_user_role1`
                                                      FOREIGN KEY (`role_id`)
                                                        REFERENCES `cash_register`.`role` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cash_register`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_register`.`user` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `login` VARCHAR(45) NOT NULL,
                                                    `email` VARCHAR(45) NOT NULL,
                                                    `password` VARCHAR(45) NOT NULL,
                                                    `role_id` INT NOT NULL,
                                                    PRIMARY KEY (`id`, `role_id`),
                                                    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
                                                    INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
                                                    CONSTRAINT `fk_user_role1`
                                                      FOREIGN KEY (`role_id`)
                                                        REFERENCES `cash_register`.`role` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cash_register`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_register`.`invoice` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `cost` VARCHAR(45) NOT NULL,
                                                       `quantity` DOUBLE NOT NULL,
                                                       `user_id` INT NOT NULL,
                                                       `user_role_id` INT NOT NULL,
                                                       PRIMARY KEY (`id`),
                                                       UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                       INDEX `fk_invoice_user1_idx` (`user_id` ASC, `user_role_id` ASC) VISIBLE,
                                                       CONSTRAINT `fk_invoice_user1`
                                                         FOREIGN KEY (`user_id`)
                                                           REFERENCES `cash_register`.`user` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cash_register`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_register`.`products` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `name` VARCHAR(45) NOT NULL,
                                                        `cost` DOUBLE NOT NULL,
                                                        `quantity` DOUBLE NOT NULL,
                                                        `invoice_id` INT NOT NULL,
                                                        PRIMARY KEY (`id`),
                                                        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                        INDEX `fk_products_invoice1_idx` (`invoice_id` ASC) VISIBLE,
                                                        CONSTRAINT `fk_products_invoice1`
                                                          FOREIGN KEY (`invoice_id`)
                                                            REFERENCES `cash_register`.`invoice` (`id`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cash_register`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cash_register`.`bill` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `totalCost` VARCHAR(45) NOT NULL,
                                                    `dates` TIMESTAMP(10) NOT NULL,
                                                    `status` VARCHAR(45) NOT NULL,
                                                    `invoice_id` INT NOT NULL,
                                                    PRIMARY KEY (`id`),
                                                    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                    INDEX `fk_bill_invoice1_idx` (`invoice_id` ASC) VISIBLE,
                                                    CONSTRAINT `fk_bill_invoice1`
                                                      FOREIGN KEY (`invoice_id`)
                                                        REFERENCES `cash_register`.`invoice` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
